# Generated by Django 6.0.6 on 2026-06-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table="task",
        ),
    ]
