# Generated by Django 6.0.6 on 2026-06-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="creat_at",
            new_name="created_at",
        ),
    ]
