# Generated by Django 6.0.6 on 2026-06-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_creat_at_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(max_length=30),
        ),
    ]
